CC=gcc
CFLAGS += -W -Wall -Wextra -Werror			#Pflicht
CFLAGS += -pedantic   						#Optional
CFLAGS += -ggdb3 -DDEBUG -fsanitize=address	#Sinnvoll für Debuging

a4_1: 
	$(CC) a4_1.c $(CFLAGS) -o a4_1  

clean:
	$(RM) a4_1

	